name: Restart Server Applications

on:
  push:
    branches:
    - main

jobs:
  restart-pm2:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: Set up SSH
      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key
          chmod 600 ssh_key

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install dependencies
        run: npm install

      - name: Install PM2 globally
        run: sudo npm install -g pm2
      
      # - name: Build the project
      #   run: npm install -g pm2

      # Step 3: Restart 10MS_Booking-management application on DO
      - name: Restart Application
        run: |
          ssh -i ssh_key ${{ secrets.USER }}@${{ secrets.HOST }} \
          "cd /root/10MS_Booking-management &&
            sudo git pull &&
            npm install &&
            pm2 reload all"
