name: Restart Server Applications

on:
  push:
    branches:
    - main

jobs:
  restart-pm2:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Step 2: Set up SSH
      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key
          chmod 600 ssh_key

      # Step 3: Restart 10MS_Booking-management application on DO
      - name: Restart Application
        run: |
          ssh -i ssh_key -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} \
          "cd /root/10MS_Booking-management && sudo git pull \
            
            apt-get install -y nodejs \


            npm install -g pm2 \

             pm2 reload all

          
          "
