name: Restart Server Application

on:
  push:
    branches:
    - main

jobs:
  restart-pm2:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Step 2: Set up SSH
      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key
          chmod 600 ssh_key

      # Step 3: Restart Stage Postal Server application on EC2
      - name: Restart Stage Postal Server Application
        run: |
          ssh -i ssh_key -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} \
          "cd /root/10MS_Booking-management && sudo git pull && pm2 reload all"
