name: Restart Server Applications

on:
  push:
    branches:
    - main

jobs:
  restart-pm2:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: Set up SSH
      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key
          chmod 600 ssh_key
      
      # - name: Build the project
      #   run: npm install -g pm2

      # Step 3: Restart 10MS_Booking-management application on DO
      - name: Restart Application
        run: |
          ssh -i ssh_key -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            
            # nvm add
             export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            
            cd /root/10MS_Booking-management
            
            # pull the updated code
            git pull

            # Restart the pm2
            pm2 reload all
          EOF

